a = int(input("Enter First Number : "))
b = int(input("Enter Second Number : "))
print("Sum of the two number is :",(a+b))
print("Difference of the two number is :",(a-b))
print("Product of the two number is :",(a*b))
print("Division of the two number is :",(a/b))
print("Remainder of 1st divided by 2nd is :",(a%b))
print("Value of 1st to the power 2nd is :",(a**b))
print("Quotient of 1st divided by 2nd is :",(a//b))