a = int(input("Enter a number :"))
b = int(input("Enter another number :"))
print("Sum is :" ,(a+b))
print("Subtraction is :" ,(a-b))
print("Product is :" ,(a*b))
print("Dvision is :" ,(a/b))
print("Exponential is :" ,(a**b))