n = input("Enter a value for type conversion :")
ch = input("Enter a character for type conversion :")
asc = int(input("Enter an ASCII value for conversion :"))
print("\nThe integer conversion of value entered is :",int(n))
print("The float conversion of value entered is :",float(n))
print("The string of value entered is :",str(asc))
print("The character conversion of value entered is :",chr(asc))
print("The integer conversion of the character entered is :",ord(ch))
print("The hexadecimal conversion of value entered is :",hex(asc))
print("The octal conversion of value entered is :",oct(asc))
